ConesaLab/SQANTI3

sqanti3_qc.py

When I provide a fofn, the script throws an error [UnboundLocalError: local variable 'files' referenced before assignment]. Once fixes, the iteration through the lines on the fofn doesn't remove training newline/white space which also results in an error.

Bams append typo fixed and rstrip added

---

utilities/report_qc/SQANTI3_report.Rmd

This fixes an error in generating the HTML report for SQANTI3 QC, as spotted by my labmates @mpmargolis and @shr4vya:
```
Quitting from lines 684-701 [p22.FSM.list] (SQANTI3_report.Rmd)
Error in `h()`:
! error in evaluating the argument 'x' in selecting a method for function 'print': no applicable method for 'layout' applied to an object of class "shiny.tag"
Backtrace:
1. base::print(...)
6. base::.handleSimpleError(...)
7. base (local) h(simpleError(msg, call))
```
The error only occurs when the input classification file to the report script contains no instances of one of the FSM subcategories: alternative_3end, alternative_3end5end, alternative_5end, or reference_match (which we noticed when running SQANTI3 on GTFs from [IsoQuant](https://github.com/ablab/IsoQuant) and …

account for possibility of null in p22.FSM.list and fix plot title

---

utilities/rescue/rescue_by_mapping_rules.R

This PR is addressing the issue [189](https://github.com/ConesaLab/SQANTI3/issues/189)
The main change is how the rescue targets are restricted to the reference isoforms. There are also several speed improvements. In some cases dplyr::filter was very slow and those were changed to simple indexing. The helper function find_best_match_id was replaced by 2 dplyr::group_by operations for speed improvement.

Updates to rescue by rules to remove 'PB.' text and speed improvements.

---

utilities/report_qc/SQANTI3_report.Rmd

Works around the problem in #221.
This may not be fully correct and only addresses HTML output.

work around ggploty errors when a structural category has no isoforms

---

utilities/short_reads.py

This modification renames the the 'ratio_TSS' column of the dataframe, this should allow us to use 4 or more SR files.

problem when using +4 SR files solved

---

sqanti3_qc.py

Separate isoforms in the classification file with ref.len < min_ref_len into a different file.

Recover isoforms shorter than min_ref_len.

---

sqanti3_qc.py

Previously, mono-exons, not classified as FSM or ISM, and contained inside a transcript, were classified as NIC. Now, only those mono-exons spaning a whole intron of the transcript are considered NIC (by intron retention), otherwise, they are considered genic.  On the other hand, mono-exons starting before the beginning or ending after the end of the reference transcript were classified as genic, even if they span a whole intron. Now, these transcripts that start/finish before/after the reference transcript and span a whole intron are classified as NIC.
While doing this I found a bug in the classification of ISM mono-exons (probably affecting a very limited number of transcripts). This has also been fixed.

Correction of the classfication of mono-exons

---

sqanti3_qc.py

Added support to also use gz compressed fastq files as isoforms input file when used as isoforms files in sqanti3_qc, and not just plain fasta.
This adds the feature requested in #312

Added compatibility for .gz compressed fasta/fastq isoforms to SQANTI3_QC

---

utilities/report_qc/SQANTI3_report.R
utilities/report_qc/SQANTI3_report.Rmd
utilities/report_qc/generatePDFreport.R

This PR fixes a few reported issues about the report failing when some categories were missing. This PR solves it by:
* Checking the existence of the plot before plotting it in .Rmd file and pdf generator file
* Improving some plots to show values of 0 when there are no transcripts in that category. The current implementation ignores those categories
This solves:
#309 
#295 
#221 
#219 
Fixes the errors the pull request #324 tries to skip

Fixes report failing when some some structural categories (mainly FSM, ISM, NIC or NNIC) were missing

---

utilities/report_qc/SQANTI3_report.R

As the existance of some variables wasn't properly checked in the report, they were either check when neded or moved to wherever could make sure that the variables do exist.

FIX: corrected unchecked existance of a variable in report when --skipORF is used

---

sqanti3_qc.py

Due to issues #334 #329  with transcripts with no explicit  (had '.' instead of + or -) that were crashing Sqanti3, those transcripts and exons have been redirected to a new file. A warning has been added during the execution to notify the user.
Solves #329 #334

FIX: transcripts without known strands (with '.' strand) are redirected

---

sqanti3_qc.py
src/commands.py

The previous state of SQANTI3 made Gmst to save the intermediate files (HMM model) into the working directory, causing errors when the run was chunked.

Fixed GMST so the HMM is saved in its directory

---

.gitignore
src/argparse_utils.py
src/classification_preprocessing.py
src/qc_argparse.py

This is a bug fix for the issue [381](https://github.com/ConesaLab/SQANTI3/issues/381), and now a single bam file can be given directly, and SQANTI3 will validate the input given to SR_bam argument

SR_bam now parses bam files directly

---

src/classification_main.py
src/parsers.py
src/utils.py

This fixes a previous issue that caused an error if the isoforms name did not have a ".". This fixes the second error posted in the issue [379](https://github.com/ConesaLab/SQANTI3/issues/379)

Updated the isoform sorting to accept a wider nomenclature

---

sqanti_reads.py

Changed the input gtf to output introns during the making of UJCs to the corrected cds gff due to incompatibilites with gtftools when running SQANTI3 with a fastq. Gtftools needs the exon lines from the gtf to have the "gene_id" flag, but this flag is not added to the corrected.gtf when the mapping step is run internally by SQANTI3. Using the cds version of the corrected gtf solves this.

changed the input gtf to output introns to the corrected cds gff

---

src/classification_steps.py

Fixed classification issue where all the junctions were being classified as novel, due to the update of the DA-pairs dictionary

Junctions classification issue fixed

---

src/parsers.py

There was a small error where if the fl file given was of a single sample, and the values were not integers, it would raise an error. This has been updated to also accept floats

Updated the fl count parser to accept floats in single samples

---

src/utilities/report_qc/SQANTI3_report.R

In some cases, if one of the junction types was missing (known or novel), there would be an error with the color pallete in R and the plots were not being created. Now, it is laxer and allows for this.
Taken from issue [390](https://github.com/ConesaLab/SQANTI3/issues/390)

Fixed report to accept classification with junction types missing

---

.github/workflows/generate-docker-image.yml
.github/workflows/push-to-dockerhub-on-release.yml

2 new github actions are added:
- generate-docker-image.yml tests that the docker image can be build
- push-to-docker-hub-on-release.yml pushes the docker image to dockerhub on release, tagging latest and the current tag that is published

Github actions: test docker build each commit, and publish to dockerhub on release

---

src/utilities/cupcake/io/GFF.py

Switches attribute parser to use regex rather than string splitting, which could return more than two items and crash where multiple >2 attributes were present.
Linked to https://github.com/ConesaLab/SQANTI3/issues/421

Switch attribute parser to regex

---

src/filter_steps.py

The -p, -n, -r parameters were not correctly added to the command. Furthermore, "-p" seemed to overload another parameter that lead to a warning, so it was changed to the longform "--TP" (and "--TN", "--remove_columns" for consistency)

Fix custom TP/TN sets and remove_columns

---

src/argparse_utils.py
src/wrapper_utils.py

Now, two more checks have been introduced in SQANTI3 qc:
1. In case the flags `--genename` or `--isoAnnotLite` are used, an error will be raised if no gene_name tag is in the input GTF attributes
2. A better warning is included in case the user includes a customized option via the `-a` flag in the wrapper

Added multiple user input checks

---

src/utilities/filter/sqanti3_rules_filter.py
test/unit/test_filter_rules.py

Categorical rules with multiple values (e.g. checking for multiple options of subcategory) were mistakenly applied via AND rather than OR - which always fails as a categorical value cannot simultaneously have multiple values. This commit explicitly parses multi-option categorical rules as lists and checks if the given value is contained.

Fix check of categorical rules with multiple values

---

src/utilities/report_qc/SQANTI3_report.R

I think the comparison for annotated should be based on the absolute value of the distance. Without abs, if the distance was -100 it would be considered annotated

Minor bug in the report
